classDiagram
CalendarHeader --* Calendar
CalendarModule --> Calendar
CalendarColumnHeader --* CalendarBody
CalendarBody --* Calendar
EventRow --* CalendarBody

class CalendarModule{
CalendarModule(date ~date~, weekStartDay~int~)<<Constructor>>
get_dateString() ~string~
get_instantiatedDate() ~Date~
getMonthObject() ~Month~
generateDateString() ~string~
getDaysInMonth() days ~Array~
getTotalDaysInMonth() ~int~
getNumberOfWeeksInMonth() ~int~
getWeekInYear(weekDateParam~date~) ~int~
getFirstDayOfWeek(dateParm~date~) ~Date~
}

class CalendarColumnHeader{
calendarColHeader ~prop~
dayDescriptorType ~prop~
}

class CalendarBody{
monthObject ~prop~
calendarColHeader ~prop~
dayDescriptorType ~prop~
events ~prop~*
 }

class EventRow{
events ~prop~
generateEventRows(events)

}


class CalendarHeader{
dateToDisplay ~prop~
displayNavArrows ~prop~
onClick()
}


class Calendar{
startDate ~prop~
startOfWeek ~prop~
dayDescriptorType ~prop~
includeHeader ~prop~
displayNavArrows ~prop~
events ~prop~*
calendarMode ~prop~*

renderCalendarStructure()
changeMonthDate()
getWeekDayNumbers()
}







